// Déclaration d'une variable qui stocke l'adresse de l'API
// Ici, la variable @src_HostAddress est définie avec la valeur "http://localhost:5000".
// Cela signifie que l'API est hébergée localement sur le port 5014.
// Cette variable peut être réutilisée dans les requêtes suivantes pour éviter la répétition de l'URL.

@src_HostAddress = http://localhost:5000

